### ISSUE TITLE
无法正常运行示例（sample.py）脚本

### ISSUE THREAD

**Issue by WalkreHuang** [clicknium/clicknium-docs#55]
**运行环境**
- 操作系统：Windows 11 家庭中文版
- VS Code：1.76.2
- Python：3.8.10
- clicknium-module：0.1.12

**问题描述**
 在 VS Code中通过 Ctrl+Shift+P 快捷键，输入 Clicknium: Sample 得到了 sample.py 文件，按 F5 运行脚本出现如下报错。
![1680060302802](https://user-images.githubusercontent.com/28650767/228418876-306f6a4c-6731-4827-ab32-30bf0cb2a58c.jpg)

**错误信息**
`c:; cd 'c:\wxApplets\demo'; & 'C:\Users\飞鱼2\AppData\Local\Programs\Python\Python38\python.exe' 'c:\wxApplets\vscode\vsExtensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '61024' '--' 'C:\wxApplets\demo\sample.py' python\debugpy\ada
Traceback (most recent call last):
  File "C:\Users\飞鱼2\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\飞鱼2\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\wxApplets\vscode\vsExtensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>   
    cli.main()
  File "c:\wxApplets\vscode\vsExtensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\wxApplets\vscode\vsExtensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\wxApplets\vscode\vsExtensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\wxApplets\vscode\vsExtensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code   
    _run_code(code, mod_globals, init_globals,
  File "c:\wxApplets\vscode\vsExtensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "C:\wxApplets\demo\sample.py", line 3, in <module>
    from clicknium import clicknium as cc, locator, ui
  File "C:\Users\飞鱼2\AppData\Local\Programs\Python\Python38\lib\site-packages\clicknium\__init__.py", line 5, in <module>
    from clicknium.core.models.web.webdriver import WebDriver
  File "C:\Users\飞鱼2\AppData\Local\Programs\Python\Python38\lib\site-packages\clicknium\core\models\web\webdriver.py", line 1, in <module>
    from clicknium.core.models.web.basewebdriver import BaseWebDriver
  File "C:\Users\飞鱼2\AppData\Local\Programs\Python\Python38\lib\site-packages\clicknium\core\models\web\basewebdriver.py", line 4, in <module>
    from clicknium.core.models.web.browser import Browser
  File "C:\Users\飞鱼2\AppData\Local\Programs\Python\Python38\lib\site-packages\clicknium\core\models\web\browser.py", line 2, in <module>
    from clicknium.core.models.web.browsertab import BrowserTab
  File "C:\Users\飞鱼2\AppData\Local\Programs\Python\Python38\lib\site-packages\clicknium\core\models\web\browsertab.py", line 6, in <module>
    from clicknium.core.models.uielement import UiElement
  File "C:\Users\飞鱼2\AppData\Local\Programs\Python\Python38\lib\site-packages\clicknium\core\models\uielement.py", line 13, in <module>
    from clicknium.core.service.invokerservice import _ConvertBaseTypeService, _ConvertOptionService, _ExceptionHandle
    import clr  File "C:\Users\飞鱼2\AppData\Local\Programs\Python\Python38\lib\site-packages\clr.py", line 6, in <module>       
    load()
  File "C:\Users\飞鱼2\AppData\Local\Programs\Python\Python38\lib\site-packages\pythonnet\__init__.py", line 143, in load
    if func(b"") != 0:  File "C:\Users\飞鱼2\AppData\Local\Programs\Python\Python38\lib\site-packages\clr_loader\types.py", line 64, in __call__
    return self._callable(ffi.cast("void*", buf_arr), len(buf_arr))RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'`

**Comment by kayYOLO** [comment]
Clicknium 的log默认存放在C:\Users\{currentUser}\AppData\Local\Clicknium\Log。 [请将日志文件打包后发送到 kay.he@clicknium.com。  可以尝试安装 [.net 4.6.2](https://dotnet.microsoft.com/zh-cn/download/dotnet-framework/thank-you/net462-web-installer) 运行 pip install --upgrade pythonnet

**Comment by WalkreHuang** [comment]
> Clicknium 的log默认存放在C:\Users{currentUser}\AppData\Local\Clicknium\Log。 [请将日志文件打包后发送到 [kay.he@clicknium.com](mailto:kay.he@clicknium.com)。 可以尝试安装 [.net 4.6.2](https://dotnet.microsoft.com/zh-cn/download/dotnet-framework/thank-you/net462-web-installer) 运行 pip install --upgrade pythonnet

日志已发送至邮箱，另外，在安装 [.net 4.6.2](https://dotnet.microsoft.com/zh-cn/download/dotnet-framework/thank-you/net462-web-installer) 时提示“这台计算机中已经安装了NET Framework 4.6.2或版本更高的更新。”
pythonnet 更新到了3.0.1 还是提示一样的错误。

**Comment by churenyouzi** [comment]
根据日志分析，麻烦切换到“C:\Users\飞鱼2\AppData\Local\Programs\Python\Python38\”，切换到Scripts文件夹，pip list看看已安装python pacakge；
其次麻烦录制或者运行sample.py的时候，麻烦提供下Windows Eventlog

**Comment by YanZhiwei** [comment]
根据日志分析，麻烦切换到“C:\Users\飞鱼2\AppData\Local\Programs\Python\Python38\”，切换到Scripts文件夹，pip list看看已安装python pacakge；
其次麻烦录制或者运行sample.py的时候，麻烦提供下Windows Eventlog

**Comment by WalkreHuang** [comment]
> 根据日志分析，麻烦切换到“C:\Users\飞鱼2\AppData\Local\Programs\Python\Python38\”，切换到Scripts文件夹，pip list看看已安装python pacakge； 其次麻烦录制或者运行sample.py的时候，麻烦提供下Windows Eventlog

pip list 如下：
![1680146190372](https://user-images.githubusercontent.com/28650767/228719609-1a95edd6-e345-4956-86f7-c3199db06574.jpg)

运行sample.py之后的 Eventlog：
![4654acbab6e4473b15e4a30ad7fdf4f](https://user-images.githubusercontent.com/28650767/228719705-113f25c5-f3ef-4010-b721-2eec717c4394.png)

![faf69a3433b6a8ca6d4ef57fed786c6](https://user-images.githubusercontent.com/28650767/228719714-8244c8a4-509d-4c13-a314-479c43a3a678.png)
